### ISSUE TITLE
Exit Code: 255(Unknown error)

### ISSUE THREAD

**Issue by paramov** [norkunas/youtube-dl-php#157]
Hi,

I keep getting this error. Can you help me? 

```
Exit Code: 255(Unknown error)

Working directory: C:\Windows\system32

 Output:
================
Fatal error: Uncaught TypeError: Argument 1 passed to YoutubeDl\YoutubeDl::YoutubeDl\{closure}() must be of the type string, null given, called in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 141 and defined in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php:60
Stack trace:
#0 C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(141): YoutubeDl\YoutubeDl::YoutubeDl\{closure}(NULL, '100%', '127.81MiB', '', '', '00:12')
#1 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1343): YoutubeDl\YoutubeDl->YoutubeDl\{closure}('out', '\n09/24 03:58:02...')
#2 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1443): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('out', '\n09/24 03:58:02...')
#3 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(430): Symfony\Component\Process\Process->readPipes(true, false)
#4 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 60

```

**Comment by norkunas** [comment]
Hi, is it related with #154 ? Could you try dev-master version?

**Comment by paramov** [comment]
Hi,

I working latest dev-master branch. This #154 issue not working on me.

> Youtube-dl latest 2021-06-06

> Windows 10

> Php 7.4

**Comment by norkunas** [comment]
Could you try to debug the output which triggers this?

**Comment by paramov** [comment]
I upgraded to stable version 2.0.1 but my problem is not solved.

here is my options;

```
Options::create()
->downloadPath(PATH . 'files/test')
->format('best')
->restrictFileNames(true)
->geoByPass()
->externalDownloader('aria2c')
->externalDownloaderArgs('-x 16 -s 16 -k 1M --file-allocation=none --async-dns=false')
->continue(true)
->cookies(PATH . 'files/cookies.txt')
->mergeOutputFormat('mp4')
->output('%(title)s.%(ext)s')
->referer('https://my.mail.ru/v/thisishorosho_tv/video/7/1166.html')
->url('https://my.mail.ru/v/thisishorosho_tv/video/7/1166.html');
```

**Comment by norkunas** [comment]
I ask to debug what the youtube-dl outputs to known what's going on, maybe wording has changed or something and it can't match anymore properly to target the processing file

**Comment by paramov** [comment]
Hi,

my fully options;

```
$yt = new YoutubeDl();

$options = Options::create()
	->downloadPath(PATH . 'files/test')
	->format('best')
	->restrictFileNames(true)
	->geoByPass()
	->externalDownloader('aria2c')
	->externalDownloaderArgs('-x 16 -s 16 -k 1M --file-allocation=none --async-dns=false')
	->continue(true)
	->cookies(PATH . 'files/cookies.txt')
	->mergeOutputFormat('mp4')
	->output('%(title)s.%(ext)s')
	->referer('https://my.mail.ru/v/thisishorosho_tv/video/7/1166.html')
	->url('https://my.mail.ru/v/thisishorosho_tv/video/7/1166.html');

$collection = $yt->download($options);

$yt->debug(function ($type, $buffer) {
    if (\Symfony\Component\Process\Process::ERR === $type) {
        echo 'ERR > ' . $buffer;
    } else {
        echo 'OUT > ' . $buffer;
    }
});

foreach ($collection->getVideos() as $video) {
	if ($video->getError() !== null){ 
		echo 'Download error' . $video->getError();
		}
	}else{	
		echo $video->getFile();

	}
}
```
But return only this error.

```
Exit Code: 255(Unknown error)

Working directory: C:\Windows\system32

 Output:
================
Fatal error: Uncaught TypeError: Argument 1 passed to YoutubeDl\YoutubeDl::YoutubeDl\{closure}() must be of the type string, null given, called in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 141 and defined in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php:60
Stack trace:
#0 C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(141): YoutubeDl\YoutubeDl::YoutubeDl\{closure}(NULL, '100%', '127.81MiB', '', '', '00:12')
#1 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1343): YoutubeDl\YoutubeDl->YoutubeDl\{closure}('out', '\n09/24 03:58:02...')
#2 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1443): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('out', '\n09/24 03:58:02...')
#3 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(430): Symfony\Component\Process\Process->readPipes(true, false)
#4 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 60
```

**Comment by norkunas** [comment]
You need to set ->debug() before the calling download :)

**Comment by paramov** [comment]
Sorry my fault :)

```
OUT > [mailru] v/thisishorosho_tv/7/1166: Downloading webpage
OUT > [mailru] v/thisishorosho_tv/7/1166: Downloading video meta JSON
OUT > [info] Writing video description metadata as JSON to: C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.info.json
[download] Destination: C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4

09/24 11:38:01 [NOTICE] Downloading 1 item(s)
[#035c4d 299MiB/300MiB(99%) CN:2 DL:5.4MiB]OUT >
09/24 11:38:43 [NOTICE] Download complete: C:/Users/paramov/Desktop/Work/www/files/test/RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
035c4d|OK  |   7.1MiB/s|C:/Users/paramov/Desktop/Work/www/files/test/RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 314594700 bytes
[download] 100% of 300.02MiB in 00:42

Fatal error: Uncaught TypeError: Argument 1 passed to YoutubeDl\YoutubeDl::YoutubeDl\{closure}() must be of the type string, null given, called in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 141 and defined in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php:60
Stack trace:
#0 C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(141): YoutubeDl\YoutubeDl::YoutubeDl\{closure}(NULL, '100%', '300.02MiB', '', '', '00:42')
#1 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1343): YoutubeDl\YoutubeDl->YoutubeDl\{closure}('out', '\n09/24 11:38:43...')
#2 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1443): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('out', '\n09/24 11:38:43...')
#3 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(430): Symfony\Component\Process\Process->readPipes(true, false)
#4 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 60
```

**Comment by norkunas** [comment]
Okay so the output is totally different than expected.. Not sure how to proceed here, should the progress callback allow null or empty string..

**Comment by paramov** [comment]
it works when i run it again after error. Sorry for my bad english.

**Comment by norkunas** [comment]
Could you try to print the all output to file and attach there? without $type only $buffer in new lines, I'll try to dig in more what's going on then. As this could be windows specifics as on ubuntu it works for me properly.
Did you change something to make it work?

**Comment by paramov** [comment]
Hi,

here is fully output;

```
C:\Users\paramov\Desktop\Work\www
λ php index.php
OUT > [mailru] v/thisishorosho_tv/7/1166: Downloading webpage
OUT > [mailru] v/thisishorosho_tv/7/1166: Downloading video meta JSON
OUT > [info] Writing video description metadata as JSON to: C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.info.json
[download] Destination: C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4

09/24 12:07:14 [NOTICE] Downloading 1 item(s)
[#97ca3a 299MiB/300MiB(99%) CN:1 DL:5.4MiB]
09/24 12:07:56 [NOTICE] Download complete: C:/Users/paramov/Desktop/Work/www/files/test/RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
97ca3a|OK  |   7.1MiB/s|C:/Users/paramov/Desktop/Work/www/files/test/RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 314594700 bytes
[download] 100% of 300.02MiB in 00:41

Fatal error: Uncaught TypeError: Argument 1 passed to YoutubeDl\YoutubeDl::YoutubeDl\{closure}() must be of the type string, null given, called in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 141 and defined in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php:60
Stack trace:
#0 C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(141): YoutubeDl\YoutubeDl::YoutubeDl\{closure}(NULL, '100%', '300.02MiB', '', '', '00:41')
#1 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1343): YoutubeDl\YoutubeDl->YoutubeDl\{closure}('out', '\r              ...')
#2 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(1443): Symfony\Component\Process\Process->Symfony\Component\Process\{closure}('out', '\r              ...')
#3 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process\Process.php(430): Symfony\Component\Process\Process->readPipes(true, false)
#4 C:\Users\paramov\Desktop\Work\www\vendor\symfony\process in C:\Users\paramov\Desktop\Work\www\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php on line 60

C:\Users\paramov\Desktop\Work\www
λ php index.php
OUT > [mailru] v/thisishorosho_tv/7/1166: Downloading webpage
OUT > [mailru] v/thisishorosho_tv/7/1166: Downloading video meta JSON
OUT > [info] Writing video description metadata as JSON to: C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.info.json
[download] C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4 has already been downloaded
[download] 100% of 300.02MiB
C:\Users\paramov\Desktop\Work\www\files\test\RAY-BAN_+_FACEBOOK_Apple_VS_Epic_Games_1_0_2021.mp4
C:\Users\paramov\Desktop\Work\www
λ
```
I didn't change anything.

**Comment by norkunas** [comment]
I meant to the file,otherwise the contents are replaced in the process

**Comment by paramov** [comment]
Yes, while some work fine, most of them fail like this.

**Fail**
- [x] https://my.mail.ru/mail/eka77739/video/_myvideo/620.html
- [x] https://my.mail.ru/mail/syskov.52/video/2629/4101.html
- [x] https://my.mail.ru/v/thisishorosho_tv/video/22/1162.html
- [x] https://my.mail.ru/v/thisishorosho_tv/video/7/1166.html

**Comment by norkunas** [comment]
I won't be able to reproduce as I'm not on Windows, so again please dump the output to the file and then attach here :)

**Comment by paramov** [comment]
I attached output. here is my composer require :)

```
"require": {
    "predis/predis": "^1.1",
    "symfony/console": "^5.2",
    "norkunas/youtube-dl-php": "dev-master"
  }
```

**Comment by norkunas** [comment]
I've added a testcase to https://github.com/norkunas/youtube-dl-php/pull/159 but it works somehow..

**Comment by paramov** [comment]
I change this line still working but i think not stable.

`static function (?string $progressTarget, string $percentage, string $size, ?string $speed, ?string $eta, ?string $totalTime): void {};`

**Comment by norkunas** [comment]
Yeah probably for more cases we need to allow null as it's not always populated :/

**Comment by paramov** [comment]
Thank you for your quick help. :)

Have a good day.

**Comment by norkunas** [comment]
You too :)
