### ISSUE TITLE
file_get_contents - No such file or directory, when video title has unsupported characters

### ISSUE THREAD

**Issue by thevalo** [norkunas/youtube-dl-php#211]
Hi, thanks for the package. Truly useful.
There's a problem linked to #113. 

When the video title has emojis or other unsupported characters, it displays the error in the title.

Any tips to fix this? Maybe rename the file with a preg_match of `/[^a-zA-Z0-9]+/` or something?

Thank you.

**Comment by thevalo** [comment]
Here's some debug:
```
OUT > [youtube] Extracting URL: https://www.youtube.com/watch?v=ziZvOyKBMXo [youtube] ziZvOyKBMXo: Downloading webpage
OUT > [youtube] ziZvOyKBMXo: Downloading ios player API JSON
OUT > [youtube] ziZvOyKBMXo: Downloading android player API JSON
OUT > [youtube] ziZvOyKBMXo: Downloading m3u8 information
OUT > [info] ziZvOyKBMXo: Downloading 1 format(s): 251 [info] Writing video metadata as JSON to: downloads\ & Andery Toronto - @spbshield VIDEO.info.json
OUT > [download] Destination: downloads\ & Andery Toronto - @spbshield VIDEO.webm [download] 0.0% of 3.09MiB at 998.17KiB/s ETA 00:03 [download] 0.1% of 3.09MiB at 2.92MiB/s ETA 00:01 [download] 0.2% of 3.09MiB at 6.82MiB/s ETA 00:00 [download] 0.5% of 3.09MiB at 7.33MiB/s ETA 00:00 [download] 1.0% of 3.09MiB at 15.15MiB/s ETA 00:00 [download] 2.0% of 3.09MiB at 20.53MiB/s ETA 00:00 [download] 4.0% of 3.09MiB at 30.60MiB/s ETA 00:00 [download] 8.0% of 3.09MiB at 36.03MiB/s ETA 00:00 [download] 16.1% of 3.09MiB at 46.02MiB/s ETA 00:00 [download] 32.3% of 3.09MiB at 9.15MiB/s ETA 00:00
OUT > [download] 64.6% of 3.09MiB at 7.25MiB/s ETA 00:00
OUT > [download] 100.0% of 3.09MiB at 6.62MiB/s ETA 00:00 [download] 100% of 3.09MiB in 00:00:00 at 6.12MiB/s [ExtractAudio] Destination: downloads\ & Andery Toronto - @spbshield VIDEO.mp3
OUT > Deleting original file downloads\ & Andery Toronto - @spbshield VIDEO.webm (pass -k to keep)

Warning: file_get_contents(downloads\ & Andery Toronto - @spbshield VIDEO.info.json): Failed to open stream: No such file or directory in C:\xxx\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php on line 18

Fatal error: Uncaught YoutubeDl\Exception\FileException: Cannot read "downloads\ & Andery Toronto - @spbshield VIDEO.info.json" file. in C:\xxx\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php:11 Stack trace: #0 C:\xxx\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php(21): YoutubeDl\Exception\FileException::cannotRead('downloads\\ & A...') #1 C:\xxx\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(165): YoutubeDl\Metadata\DefaultMetadataReader->read('downloads\\ & A...') #2 C:\xxx\index.php(59): YoutubeDl\YoutubeDl->download(Object(YoutubeDl\Options)) #3 {main} thrown in C:\xxx\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php on line 11
```

The filename is: `Лёша Стелит & Andery Toronto - Стая [@spbshield]`, and NOT ` & Andery Toronto - @spbshield VIDEO`.
That's why it is failing to read this file. 

Also, I've noticed that I have to manually delete the files after downloading (by using `unlink()`) because it does not delete then itself? Speaking about examples where's no Unicode characters which it works good.

**Comment by thevalo** [comment]
Adding `--restrict-filenames` fixes the problem, but it leaves only A-Z standard ASCII chars.

**Comment by norkunas** [comment]
Hello,
I think that's related to Windows behavior.. will see if there are any solutions

**Comment by norkunas** [comment]
> Also, I've noticed that I have to manually delete the files after downloading (by using `unlink()`) because it does not delete then itself?

If a fatal error occurs before cleaning up, then yes

**Comment by norkunas** [comment]
In your debug snippet there was:
`Fatal error: Uncaught YoutubeDl\Exception\FileException: Cannot read "downloads\ & Andery Toronto - @spbshield VIDEO.info.json" file. in C:\xxx\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php:11 Stack trace: #0 C:\xxx\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php(21): YoutubeDl\Exception\FileException::cannotRead('downloads\\ & A...') #1 C:\xxx\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(165): YoutubeDl\Metadata\DefaultMetadataReader->read('downloads\\ & A...') #2 C:\xxx\index.php(59): YoutubeDl\YoutubeDl->download(Object(YoutubeDl\Options)) #3 {main} thrown in C:\xxx\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php on line 11`

So I'm referring to this fatal error, than blocks from cleaning up.
I was on holiday so I need to catch up, will get back to you soon

**Comment by thevalo** [comment]
@norkunas - Ah, I missed that. But I think that's merely linked to the main issue here since when it can't read, it can't also delete. Thank you, and have a nice holiday!

**Comment by thevalo** [comment]
@norkunas strangely when using `yt-dlp` CLI for the aforementioned video, it works well i.e.: it can be downloaded as it is:
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=ziZvOyKBMXo
[youtube] ziZvOyKBMXo: Downloading webpage
[youtube] ziZvOyKBMXo: Downloading ios player API JSON
[youtube] ziZvOyKBMXo: Downloading android player API JSON
[youtube] ziZvOyKBMXo: Downloading m3u8 information
[info] ziZvOyKBMXo: Downloading 1 format(s): 22
[download] Destination: Лёша Стелит & Andery Toronto - Стая @spbshield VIDEO [ziZvOyKBMXo].mp4
[download] 100% of   16.98MiB in 00:00:03 at 5.38MiB/s
```
However when using via youtube-dl-php, it ain't working. Any thoughts?

**Comment by norkunas** [comment]
Could you try to edit `src/Process/DefaultProcessBuilder.php`:
line
`$process = new Process($arguments);`
to
`$process = new Process($arguments, null, ['LANG' => 'en_US.UTF-8']);`

or paste what `var_dump($_SERVER)` prints?

**Comment by thevalo** [comment]
@norkunas I tried the change you've suggested but to no avail.

Here's the var_dump:
```
array(34) { ["HTTP_HOST"]=> string(13) "project.test" ["HTTP_CONNECTION"]=> string(10) "keep-alive" ["HTTP_UPGRADE_INSECURE_REQUESTS"]=> string(1) "1" ["HTTP_USER_AGENT"]=> string(111) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ["HTTP_ACCEPT"]=> string(135) "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" ["HTTP_ACCEPT_ENCODING"]=> string(13) "gzip, deflate" ["HTTP_ACCEPT_LANGUAGE"]=> string(14) "en-US,en;q=0.9" ["PATH"]=> string(1252) "C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.54-win64-VS16\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-8.0.30-winx64\bin;C:\laragon\bin\nginx\nginx-1.22.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v18;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-8.1.10-Win32-vs16-x64;C:\laragon\bin\python\python-3.10;C:\laragon\bin\python\python-3.10\Scripts;C:\laragon\bin\redis\redis-x64-5.0.14.1;C:\laragon\bin\telnet;C:\laragon\usr\bin;C:\Users\xxx\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\xxx\AppData\Roaming\Composer\vendor\bin;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxx\AppData\Local\GitHubDesktop\bin;C:\Program Files\mitmproxy\bin" ["SystemRoot"]=> string(10) "C:\WINDOWS" ["COMSPEC"]=> string(27) "C:\WINDOWS\system32\cmd.exe" ["PATHEXT"]=> string(53) ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC" ["WINDIR"]=> string(10) "C:\WINDOWS" ["SERVER_SIGNATURE"]=> string(0) "" ["SERVER_SOFTWARE"]=> string(47) "Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.1.10" ["SERVER_NAME"]=> string(13) "project.test" ["SERVER_ADDR"]=> string(9) "127.0.0.1" ["SERVER_PORT"]=> string(2) "80" ["REMOTE_ADDR"]=> string(9) "127.0.0.1" ["DOCUMENT_ROOT"]=> string(23) "C:/laragon/www/project" ["REQUEST_SCHEME"]=> string(4) "http" ["CONTEXT_PREFIX"]=> string(0) "" ["CONTEXT_DOCUMENT_ROOT"]=> string(23) "C:/laragon/www/project" ["SERVER_ADMIN"]=> string(17) "admin@example.com" ["SCRIPT_FILENAME"]=> string(33) "C:/laragon/www/project/index.php" ["REMOTE_PORT"]=> string(5) "60431" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["REQUEST_URI"]=> string(1) "/" ["SCRIPT_NAME"]=> string(10) "/index.php" ["PHP_SELF"]=> string(10) "/index.php" ["REQUEST_TIME_FLOAT"]=> float(1696342410.494605) ["REQUEST_TIME"]=> int(1696342410) }
```

**Comment by norkunas** [comment]
Did you try to run your script in cli? Does it have same problem?

**Comment by thevalo** [comment]
Here's fresh error log:
```
[03-Oct-2023 14:26:26 UTC] PHP Warning:  file_get_contents(downloads\   .info.json): Failed to open stream: No such file or directory in C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php on line 18
[03-Oct-2023 14:26:26 UTC] PHP Fatal error:  Uncaught YoutubeDl\Exception\FileException: Cannot read "downloads\   .info.json" file. in C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php:11
Stack trace:
#0 C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php(21): YoutubeDl\Exception\FileException::cannotRead('downloads\\   .i...')
#1 C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(166): YoutubeDl\Metadata\DefaultMetadataReader->read('downloads\\   .i...')
#2 C:\laragon\www\project\index.php(54): YoutubeDl\YoutubeDl->download(Object(YoutubeDl\Options))
#3 {main}
  thrown in C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php on line 11
```

**Comment by norkunas** [comment]
I meant not running the yt-dlp directly,but running your php script via cli

**Comment by thevalo** [comment]
Sorry! Here's the info you requested:
```
array(67) {
  ["ALLUSERSPROFILE"]=>
  string(14) "C:\ProgramData"
  ["APPDATA"]=>
  string(29) "C:\Users\xxx\AppData\Roaming"
  ["CommonProgramFiles"]=>
  string(29) "C:\Program Files\Common Files"
  ["CommonProgramFiles(x86)"]=>
  string(35) "C:\Program Files (x86)\Common Files"
  ["CommonProgramW6432"]=>
  string(29) "C:\Program Files\Common Files"
  ["COMPUTERNAME"]=>
  string(15) "DESKTOP-XXXXXX"
  ["ComSpec"]=>
  string(27) "C:\WINDOWS\system32\cmd.exe"
  ["DriverData"]=>
  string(38) "C:\Windows\System32\Drivers\DriverData"
  ["FPS_BROWSER_APP_PROFILE_STRING"]=>
  string(17) "Internet Explorer"
  ["FPS_BROWSER_USER_PROFILE_STRING"]=>
  string(7) "Default"
  ["HOMEDRIVE"]=>
  string(2) "C:"
  ["HOMEPATH"]=>
  string(11) "\Users\xxx"
  ["IDEA_VM_OPTIONS"]=>
  ["LOCALAPPDATA"]=>
  string(27) "C:\Users\xxx\AppData\Local"
  ["LOGONSERVER"]=>
  string(17) "\\DESKTOP-XXXXXX"
  ["NUMBER_OF_PROCESSORS"]=>
  string(1) "4"
  ["OneDrive"]=>
  string(22) "C:\Users\xxx\OneDrive"
  ["OS"]=>
  string(10) "Windows_NT"
  ["Path"]=>
  string(1292) "C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.54-win64-VS16\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-8.0.30-winx64\bin;C:\laragon\bin\nginx\nginx-1.22.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v18;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-8.1.10-Win32-vs16-x64;C:\laragon\bin\python\python-3.10;C:\laragon\bin\python\python-3.10\Scripts;C:\laragon\bin\redis\redis-x64-5.0.14.1;C:\laragon\bin\telnet;C:\laragon\usr\bin;C:\Users\xxx\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\xxx\AppData\Roaming\Composer\vendor\bin;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxx\AppData\Local\GitHubDesktop\bin;;C:\Program Files\Azure Data Studio\bin;C:\Program Files\mitmproxy\bin"
  ["PATHEXT"]=>
  string(53) ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
  ["PROCESSOR_ARCHITECTURE"]=>
  string(5) "AMD64"
  ["PROCESSOR_IDENTIFIER"]=>
  string(50) "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel"
  ["PROCESSOR_LEVEL"]=>
  string(1) "6"
  ["PROCESSOR_REVISION"]=>
  string(4) "5e03"
  ["ProgramData"]=>
  string(14) "C:\ProgramData"
  ["ProgramFiles"]=>
  string(16) "C:\Program Files"
  ["ProgramFiles(x86)"]=>
  string(22) "C:\Program Files (x86)"
  ["ProgramW6432"]=>
  string(16) "C:\Program Files"
  ["PROMPT"]=>
  string(4) "$P$G"
  ["PSModulePath"]=>
  string(149) "C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Message Analyzer\PowerShell\"
  ["PUBLIC"]=>
  string(15) "C:\Users\Public"
  ["SESSIONNAME"]=>
  string(7) "Console"
  ["SystemDrive"]=>
  string(2) "C:"
  ["SystemRoot"]=>
  string(10) "C:\WINDOWS"
  ["TEMP"]=>
  string(32) "C:\Users\xxx\AppData\Local\Temp"
  ["TMP"]=>
  string(32) "C:\Users\xxx\AppData\Local\Temp"
  ["USERDOMAIN"]=>
  string(15) "DESKTOP-XXXXXX"
  ["USERDOMAIN_ROAMINGPROFILE"]=>
  string(15) "DESKTOP-XXXXXX"
  ["USERNAME"]=>
  string(4) "Twin"
  ["USERPROFILE"]=>
  string(13) "C:\Users\xxx"
  ["windir"]=>
  string(10) "C:\WINDOWS"
  ["ZES_ENABLE_SYSMAN"]=>
  string(1) "1"
  ["PHP_SELF"]=>
  string(9) "index.php"
  ["SCRIPT_NAME"]=>
  string(9) "index.php"
  ["SCRIPT_FILENAME"]=>
  string(9) "index.php"
  ["PATH_TRANSLATED"]=>
  string(9) "index.php"
  ["DOCUMENT_ROOT"]=>
  string(0) ""
  ["REQUEST_TIME_FLOAT"]=>
  float(1696400004.393583)
  ["REQUEST_TIME"]=>
  int(1696400004)
  ["argv"]=>
  array(1) {
    [0]=>
    string(9) "index.php"
  }
  ["argc"]=>
  int(1)
}
```

**Comment by norkunas** [comment]
And running in this way still does not work?

**Comment by thevalo** [comment]
Nope, here's the log:
```
C:\laragon\www\project>php index.php "v=https://www.youtube.com/watch?v=XuLJkX7ybF8"

Warning: file_get_contents(https://api.telegram.org/botXXXXXXXX/sendMessage?text=OK...): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in C:\laragon\www\project\index.php on line 77

Warning: file_get_contents(downloads\   .info.json): Failed to open stream: No such file or directory in C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php on line 18

Fatal error: Uncaught YoutubeDl\Exception\FileException: Cannot read "downloads\   .info.json" file. in C:\laragon\www\project\vendor\norkunas\youtube-dl-php\src\Exception\FileException.php:11
```

**Comment by norkunas** [comment]
I'm out of ideas :disappointed:

**Comment by thevalo** [comment]
No problem! Thank you for consideration and this time. If I find a solution, I'll be sure to post it here. Regards.
